{
  pkgs,
  inputs,
  ...
}:

{
  home.packages = with pkgs; [
    fd
    ripgrep
    fzf
    bat
    eza
    jq
    hurl
    process-compose
    aspell
    figlet
    glow
    gum
    vhs
    mailpit
    lazysql
    sqlit-tui
    visidata
    csvlens
    dua
    dust
    mysql84
    postgresql_17
    redis
    opencode
    grok-build
    herdr
    caddy
    inputs.nixpkgs-devenv.legacyPackages.${pkgs.stdenv.hostPlatform.system}.devenv
    just
    (callPackage ./_pkgs/ldcli.nix { })
    (callPackage ./_pkgs/backlog.nix { })
    rustfs
    graphite-cli
    inputs.tuicr.packages.${pkgs.stdenv.hostPlatform.system}.default
    prek
    superfile
    taskwarrior3
    rdap
    sops
    age
    croc
    ffmpeg
    yt-dlp
    laravel
    cliamp
    terminal-notifier
    llmfit
    defuddle
    abtop
    fastfetch

    nil
    nixfmt
    statix
    deadnix

    intelephense
    phpantom-lsp
    typescript-language-server
    vscode-langservers-extracted
    svelte-language-server
    vue-language-server
    yaml-language-server
    bash-language-server
    lua-language-server
    gopls
    marksman
    taplo
    tailwindcss-language-server
    astro-language-server
  ];
}
